// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AdditionalSkillsTable: typeof import('./src/components/AdditionalSkillsTable.vue')['default']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AImage: typeof import('ant-design-vue/es')['Image']
    AInput: typeof import('ant-design-vue/es')['Input']
    AnomaliesTab: typeof import('./src/components/AnomaliesTab.vue')['default']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    PickBanTab: typeof import('./src/components/PickBanTab.vue')['default']
    ResultFavoriteRow: typeof import('./src/components/ResultFavoriteRow.vue')['default']
    ResultFavoriteTab: typeof import('./src/components/ResultFavoriteTab.vue')['default']
    SearchFavoriteTab: typeof import('./src/components/SearchFavoriteTab.vue')['default']
    SimulateResultRow: typeof import('./src/components/SimulateResultRow.vue')['default']
    SimulateResultTable: typeof import('./src/components/SimulateResultTable.vue')['default']
    SimulateTab: typeof import('./src/components/SimulateTab.vue')['default']
    StatTable: typeof import('./src/components/StatTable.vue')['default']
    TalismansTab: typeof import('./src/components/TalismansTab.vue')['default']
  }
}
