pub const MAX_ANSWER_LENGTH: usize = 200;

pub const MAX_SLOT_LEVEL: usize = 4;
pub const SKILLS_COUNT: usize = 140;
pub const EQUIP_PART_COUNT: usize = 6;

// 6 = DEFENSE + 5 RESISTS TYPES
pub const CALC_VEC_SLOTS_OFFSET: usize = EQUIP_PART_COUNT + 6;
pub const CALC_VEC_SKILLS_OFFSET: usize = CALC_VEC_SLOTS_OFFSET + MAX_SLOT_LEVEL;
pub const CALC_VEC_LENGTH: usize = CALC_VEC_SKILLS_OFFSET + MAX_SLOT_LEVEL + SKILLS_COUNT;
